-- DecoSun Mercado Publico v2 - Fix upsert conflict target.
--
-- Purpose:
-- Replace the partial unique index on market_opportunities(source, external_id)
-- with a complete unique index so Supabase/PostgREST can use it reliably as
-- the arbiter for upsert(..., { onConflict: "source,external_id" }).
--
-- Run these diagnostics manually before applying if the migration fails or if
-- you suspect legacy duplicated/null opportunity identifiers:
--
-- select source, external_id, count(*)
-- from public.market_opportunities
-- group by source, external_id
-- having count(*) > 1;
--
-- select count(*)
-- from public.market_opportunities
-- where source is null or external_id is null;
--
-- PostgreSQL unique indexes allow multiple null values, but new Radar records
-- generated by importar-recomendadas always set source and external_id.

drop index if exists public.idx_market_opportunities_source_external_id;

create unique index if not exists idx_market_opportunities_source_external_id
on public.market_opportunities(source, external_id);
