import { useMemo, useState } from "react"
import { DEFAULT_PROFILE_LENGTH_CM, DEFAULT_ROLL_WIDTH_CM, optimizeFabricByMode, optimizeProfiles } from "../../lib/cuttingOptimizer"

const tabs = [["order", "OT calculada"], ["fabric", "Optimización tela"], ["profiles", "Perfiles / componentes"]]
const cm = (value) => `${Number(value || 0).toFixed(1)} cm`

export default function ProductionOptimizer({ calculation }) {
  const [tab, setTab] = useState("order")
  const [rollWidth, setRollWidth] = useState(DEFAULT_ROLL_WIDTH_CM)
  const [mode, setMode] = useState("same-height")
  const [profileLength, setProfileLength] = useState(DEFAULT_PROFILE_LENGTH_CM)
  const fabricOptimization = useMemo(() => optimizeFabricByMode(calculation.pieces || [], rollWidth, mode), [calculation.pieces, rollWidth, mode])
  const profiles = useMemo(() => optimizeProfiles(calculation.pieces || [], profileLength), [calculation.pieces, profileLength])
  if (!calculation.pieces?.length) return <section className="treasury-table operations-section"><div className="operations-empty"><strong>Aún no hay una OT calculada.</strong><span>Calcula materiales primero para habilitar las vistas de fabricación.</span></div></section>
  return <>
    <div className="operations-subtabs">{tabs.map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === "order" && <section className="treasury-table operations-section"><div className="section-heading"><div><h2>Orden de trabajo</h2><p>{calculation.pieces.length} cortinas calculadas.</p></div></div><div className="operations-table-scroll"><table><thead><tr><th>N°</th><th>Tipo</th><th>Ancho final</th><th>Alto final</th><th>Vano</th><th>Tela</th><th>Ancho tela</th><th>Alto corte</th><th>Cenefa</th><th>Tubo Ø38</th><th>Redondo</th><th>Contrapeso</th><th>Barra inf.</th><th>Mecanismo</th><th>Lugar</th><th>Caída</th><th>Izq/Der</th></tr></thead><tbody>{calculation.pieces.map((piece) => <tr key={piece.id}><td>{piece.number}</td><td>{piece.productLabel}</td><td>{cm(piece.width)}</td><td>{cm(piece.height)}</td><td>{piece.opening || "—"}</td><td>{piece.fabric}</td><td>{cm(piece.fabricWidth)}</td><td>{cm(piece.fabricHeight)}</td><td>{piece.valance ? cm(piece.valance) : "—"}</td><td>{piece.tube ? cm(piece.tube) : "—"}</td><td>{piece.round ? cm(piece.round) : "—"}</td><td>{piece.counterweight ? cm(piece.counterweight) : "—"}</td><td>{piece.bottomBar ? cm(piece.bottomBar) : "—"}</td><td>{piece.mechanism}</td><td>{piece.place || "—"}</td><td>{piece.drop || "—"}</td><td>{piece.side || "—"}</td></tr>)}</tbody></table></div></section>}
    {tab === "fabric" && <section className="treasury-table operations-section"><div className="operations-controls"><label>Ancho rollo (cm)<input type="number" min="1" value={rollWidth} onChange={(e) => setRollWidth(Number(e.target.value))} /></label><label>Modo<select value={mode} onChange={(e) => setMode(e.target.value)}><option value="same-height">Priorizar mismo alto</option><option value="max-width">Maximizar ancho</option></select></label></div>{fabricOptimization.rejected.length > 0 && <div className="operations-warning"><strong>Excede ancho disponible</strong>{fabricOptimization.rejected.map((piece) => <span key={piece.id}>OT #{piece.number}: {cm(piece.fabricWidth)} para rollo de {cm(rollWidth)}. No incluida en la optimización.</span>)}</div>}<div className="operations-cut-list">{fabricOptimization.rows.map((row, index) => <article key={`${row.id}-${index}`}><header><strong>{row.fabric} · pasada {index + 1} · {row.label}</strong><span>{cm(row.height)} lineales · sobrante {cm(row.remaining)}</span></header><div className="operations-cut-bar">{row.items.map((piece) => <span key={piece.id} style={{ width: `${Math.min(100, piece.fabricWidth / rollWidth * 100)}%` }}>{cm(piece.fabricWidth)}</span>)}</div></article>)}</div></section>}
    {tab === "profiles" && <section className="treasury-table operations-section"><div className="operations-controls"><label>Largo perfil (cm)<input type="number" min="1" value={profileLength} onChange={(e) => setProfileLength(Number(e.target.value))} /></label></div>{profiles.map((profile) => <div className="operations-profile-group" key={profile.name}><h3>{profile.name} · {profile.bars.length} perfil(es) · compra informativa: {profile.packages} paquete(s) de 10</h3>{profile.rejected.length > 0 && <div className="operations-warning"><strong>Excede largo de perfil</strong>{profile.rejected.map((piece) => <span key={piece.id}>OT #{piece.number}: {cm(piece[profile.field])} para perfil de {cm(profile.length)}. No incluido en la optimización.</span>)}</div>}<div className="operations-cut-list">{profile.bars.map((bar, index) => <article key={index}><header><strong>Perfil {index + 1}</strong><span>Sobrante {cm(bar.remaining)}</span></header><div className="operations-cut-bar">{bar.items.map((piece) => <span key={piece.id} style={{ width: `${Math.min(100, piece[profile.field] / profile.length * 100)}%` }}>{cm(piece[profile.field])}</span>)}</div></article>)}</div></div>)}</section>}
  </>
}
